### ISSUE TITLE
Prism Validation Strategy

### ISSUE THREAD

**Issue by barrett-schonefeld** [stoplightio/prism#1063]
For now, this is just a general question. Feel free to close this issue once we have discussed the issue.

After exploring Prism's validation code for a bit, I have a couple questions.

My understanding of the process:

1. Identify the expected schema using the operation and the status code.
2. Pass the header to the header validation functions, pass the body to the body validation functions, etc.
3. Identify and record any errors.

Question:

In a previous issue, I mentioned that I'm considering Prism for a endpoint validation project that requires request generation. For the same project, we need to implement some of our validation rules from our API handbook. The following question (I promise there is a question at the end) is about extending the validation rules.

It seems to me that the header validation, for example, is done only with the header information, and body parameter validation is only (or mostly) done with mediaType and the schema.

If I wanted to implement validation that coupled the header information in the request with the status code of the response, it seems that this would require a structural change in the validation. Based on your deeper knowledge of the project, would coupling currently unrelated data (requests and response headers, response body and status code, etc.) require big changes to the structure of the validation such that my team would need to fork and maintain a separate version of Prism?

**Comment by XVincentX** [comment]
@barrett-schonefeld 

It is hard to give a meaningful answer without having an example of what you're trying to achieve.

We base our validations exclusively on what's in the OpenAPI 2/3 document; we don't go further as we can't really guess what the user wants. Let's continue the discussion here — in meantime I'll close the issue since there's no action point in our code.

**Comment by barrett-schonefeld** [comment]
@XVincentX 

Examples:

1. Request has a `request body`, but the `Content-Type` is not supported by the API. I would like to validate that the status code is `415`.

2. Validate that a `201` response has a `Location` header with the URI of the resource.

**Comment by XVincentX** [comment]
1. Prism can do that without any changes. In an OpenAPI document you can define the returned media types — if none of these matches the one described in the `Accept` header, the 415 response will be generated for you
2. This can be enforced using the `headers` part of the response of an OpenAPI request and mark it as required/mandatory in the schema
3. This is effectively not something that you can do in Prism.

>  It seems to me that these two examples, using the current data available to each Prism validator (header, body, etc.), could not be added to the set of validation rules. 

This is kind of correct. The validators validate only in their context and cannot access other parts of the request (as in, the header validator cannot see the request body) and vice versa.

> Second, would providing the necessary data to each Prism validator be feasible

It is feasible but I'd be kind of skeptical about adding such thing in Prism. What you're leaning is more on a runtime validator rather than a mock server, and I am not too sure this is something we want to solve with this project. Maybe in the hosted version powered by Stoplight we might have some margins to leverage that.

**Comment by barrett-schonefeld** [comment]
@XVincentX great, thank you for the feedback!
