### ISSUE TITLE
Postman plus Prism Proxy causes errors

### ISSUE THREAD

**Issue by lornajane** [stoplightio/prism#1064]
**Describe the bug**
I use Postman (https://www.postman.com/) with Prism, with good results. When I put Prism into proxy mode, Postman thinks it didn't get a response (but curl to the same endpoint works fine).

Prism shows no error messages, the output from Prism is identical whether I make the request through Postman or curl

Postman's console says "incorrect header check"

curl shows that Prism is returning a header `content-encoding: gzip`, which I don't get when I request the live API directly rather than via the Prism proxy.

**To Reproduce**

1. Given this OpenAPI document (actually I'm not sure it matters but I'm using https://github.com/Nexmo/api-specification/blob/master/definitions/verify.yml and hitting the `search/` endpoint
2. Run this CLI command `prism proxy verify.yml https://api.nexmo.com/verify`
3. Make a request to the Search endpoint using Postman

**Expected behavior**
The API response

**Environment (remove any that are not applicable):**
 - Library version: 3.2.9
 - OS: Ubuntu 18.04
 - Postman 7.21.1
 - curl: 7.58.0

**Additional context**
I managed to get things working by adding an additional header to Postman `Accept-Encoding` and leaving it empty - I think Postman sends this header by default. However curl does not send `Accept-Encoding` by default and I still see that Prism returns a `content-encoding: gzip` to curl so while I'm not sure Postman is sending correct headers, I think Prism is also adding something here that doesn't help!

**Comment by XVincentX** [comment]
I am not experiencing this behaviour @lornajane — can you check out if I am reproducing correctly?

1. Run Prism mock on the nexmo API Server

<img width="1078" alt="image" src="https://user-images.githubusercontent.com/1416224/78037192-d35e0480-7330-11ea-8f12-5e31c6e899d7.png">


2. Use Postman to run a request:

<img width="1164" alt="image" src="https://user-images.githubusercontent.com/1416224/78037210-dbb63f80-7330-11ea-94d9-8739999fcc84.png">

3. Get Missing API Key error

<img width="600" alt="image" src="https://user-images.githubusercontent.com/1416224/78037235-e2dd4d80-7330-11ea-8aec-c0cc499ea7ab.png">

**Comment by XVincentX** [comment]
@lornajane Feel free to reopen once you have more informations for us.

**Comment by hilary** [comment]
Thanks @lornajane, your workaround is working for us, too.

Hi @XVincentX. We're also having the same problem. To reproduce, run

```
prism proxy ...
```

*not*

```
prism mock ...
```

The problem we're encountering is with Postman (and `newman`) through `prism` running as a *validation proxy*. We also encountered the same problem using `httpie` with `prism proxy`.

As best we can tell, the problem is happening because:

1. a client is adding a default) `Accept-Encoding: gzip, deflate` header to requests
1. the response isn't, in fact, encoded/gzipped (the spec does not specify it as such and the live API doesn't return gzipped responses)
1. prism proxy is trying to gunzip the response for some reason (as part of validation?), despite it not being in the spec/contract

When the header is not sent by the client, everything works fine.

Whether the header is sent by the client or not should not affect the behavior of the validation proxy, given that the spec does not specify that the response is encoded.

**Comment by XVincentX** [comment]
@hilary Thanks for the detailed explanation! With these new details I'll reopen the issue and try to reproduce!

**Comment by XVincentX** [comment]
@lornajane @hilary Hey!

Can you please try https://github.com/stoplightio/prism/pull/1309 and give me some feedback? It seems like Prism was proactively asking for a compressed response when used as a Proxy — I've disabled that so it behaves more like… a proxy :trollface:

**Comment by lornajane** [comment]
Hey, I realise you already closed this already but I would like to be able to test branches more easily. I'm struggling to run locally from source ... are the instructions in `CONTRIBUTING.md` still the best place to look?

**Comment by XVincentX** [comment]
@lornajane Yes! Are you receiving any specific error?

```bash
cd packages/cli

yarn cli:debug mock file.oas.yml
```

**Comment by lornajane** [comment]
Since I don't have a debugger set up, I was struggling (javascript is not a main tech stack for me). I got it to work (after upgrading nodejs from 10.x to 14.x) with `cd packages/cli` then `yarn install` and `yarn run cli mock [spec]`.

First of all: I can replicate my original proxy issue with postman and curl when I have tag v3.3.6 checked out locally. Good start!
Switch to master branch, and I get different behaviour. Curl works fine and I do not see the `content-encoding` header. Postman however gets a fetch error with `reason: Unexpected token  in JSON at position 0` (did that even paste? I'll screenshot).

![image](https://user-images.githubusercontent.com/172607/88582000-eade9d00-d045-11ea-88da-5a2c531d29f1.png)

Still digging ...

**Comment by XVincentX** [comment]
@lornajane It's not a big deal, but keep in mind that Prism has not been tested on Node 14; the best would be to stick to node 12 for now.

**Comment by lornajane** [comment]
OK. I can replicate this second problem AND changing the `Accept-Encoding` header in Postman makes it go away, but I cannot understand what could cause it! Does something that parses JSON care about the headers it arrived with? I am going to paste mine while I'm looking at this thing:

```
< HTTP/1.1 200 OK
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Headers: *
< Access-Control-Allow-Credentials: true
< Access-Control-Expose-Headers: *
< date: Mon, 27 Jul 2020 19:37:57 GMT
< content-type: application/json
< Content-Length: 49
< set-cookie: __cfduid=d87afc6a400f6b945325c0d15cecc74f51595878676; expires=Wed, 26-Aug-20 19:37:56 GMT; path=/; domain=.nexmo.com; HttpOnly; SameSite=Lax
< cache-control: max-age=1
< x-frame-options: deny
< x-xss-protection: 1; mode=block;
< strict-transport-security: max-age=31536000; includeSubdomains
< x-content-type-options: nosniff
< content-disposition: attachment; filename="api.txt"
< x-nexmo-trace-id: 626d33170314f6632e914091f742c1fd
< cf-cache-status: DYNAMIC
< cf-request-id: 04336144af0000e68cf8358200000001
< expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
< server: cloudflare
< cf-ray: 5b98d126ba45e68c-LHR
< Connection: keep-alive
```

Running another copy of Prism locally to fake the remote API doesn't produce the same error; the content lengths of the two responses are identical but the "real" one has more headers. I think we should not do anything for now - the original bug I reported may well be fixed. But I've put all the info I have here in the hope that we will find it if it comes up again; basically something live API (local Prism spec does not replicate) causes Prism to send me a FetchError and a JSON parsing error if the default Postman header `Accept-Encoding: gzip, deflate, br` is included. The workaround is still to suppress that header, but I'm not sure what it can cause in the response that scares prism so much :/

**Comment by XVincentX** [comment]
I think I understand the reason. Essentially your server is returning a gzipped response and Prism is not extracting it because of the compression disabled. I'll have to workaround this in another way.

@lornajane https://github.com/stoplightio/prism/pull/1319 This will probably fix your issue. Can you try that out?

**Comment by arunvangapelli** [comment]
@XVincentX I saw the updates and tested with new prism versions. I tested with 3.3.7, then updated to 4.0.0 and tested with that too. I'm still getting **Error: incorrect header check**

One of my colleagues who is starting with prism also tried it and got a different error as part of that testing, **Error: Decompression failed**
I'm attaching files to reproduce **Error: Decompression failed** (Used http://reqres.in API for testing.)

[prism_testing.zip](https://github.com/stoplightio/prism/files/5132551/prism_testing.zip)


**prism command used:**
prism proxy prismtest.oas2.json http://reqres.in -p 4014


**Versions used in testing:**
Node version: 12.8.3
prism version: 3.3.7 and also 4.0.0

and

Node version: 14.3.0
prism version: 3.3.7 and also 4.0.0

Let me know if I need to create a new issue, since this is closed.

**Comment by XVincentX** [comment]
I cannot reproduce the issue with the OpenAPI document you provided; can you help me out?

<img width="983" alt="image" src="https://user-images.githubusercontent.com/1416224/91426037-3dd18d00-e85c-11ea-811e-3efbc0528ee5.png">

**Comment by arunvangapelli** [comment]
![curl_testing_success](https://user-images.githubusercontent.com/2313667/91482728-61e09e80-e85b-11ea-9608-844e3cf22b11.png)

@XVincentX Tested with curl, similar to your testing there is no issue for me.

The issue is when using postman or postman's newman cli. We use newman in our pipelines for end-to-end testing to run our postman collections.

Below are the results when testing with postman tool and newman cli.
Ignore **Verfiy any standard api** in the below screenshots.

**1. newman v4.5.5 testing:** (local test)
![newman_v4 5 5_testing_error](https://user-images.githubusercontent.com/2313667/91483070-f814c480-e85b-11ea-916a-fa6c8d727c16.png)
 
**2. postman v7.31.1 testing**
![postman_v7 31 1_testing_error](https://user-images.githubusercontent.com/2313667/91483182-25617280-e85c-11ea-9488-900f385b0b60.png)

**3. newman v5.1.2 testing** (pipelines test)
![newman_v5 1 2_testing_error](https://user-images.githubusercontent.com/2313667/91483233-37431580-e85c-11ea-8c38-025a08a3ff39.png)

You should be able to reproduce the issue with postman or newman cli. Let me know if you need more info.

Thanks.

**Comment by mimkorn** [comment]
I'm facing the same issue on Prism 4.1.2

I noticed it when trying to access an API via browser — I'd get `Content Encoding Error` on Firefox, a blank page on Brave and in Postman I'm getting "Incorrect Header check" as in the initial post.
<img width="557" alt="CleanShot 2021-04-07 at 16 20 39@2x" src="https://user-images.githubusercontent.com/5420435/113881971-33e21600-97bd-11eb-8d63-90d3cdc95095.png">

**Reproduction**
The API I'm hitting is 
`curl -u superuser:superuser https://demo.magnolia-cms.com/.rest/template-definitions/v1/mtk:components/link`
It should return a simple JSON document. However, when that is hit via Prism proxy, it returns result only via curl. 
For the proxy, you can use this simple openapi spec: https://pastebin.com/U9TUrj9u

`prism proxy *file from above link* https://demo.magnolia-cms.com/.rest/ --errors -p 5003`

**Comment by ondrakoupil** [comment]
I am facing this issue too. Prism 4.1.2, node.js both 12.19.1 and 14.15.1.

It is clearly not specific to Postman. From my observation, the issue can be generalised as this:

- Client send request to Prism proxy with `Accept-Encoding: gzip` header
- Proxy forwards the request to upstream server with that header
- Upstream returns gzipped (binary) body with `Content-Encoding: gzip` header
- Proxy forwards it back to client, keeping the `Content-Encoding: gzip` header BUT with un-gzipped (decoded) body
- Client is confused because it got content marked as gzipped, but in fact, it is already decoded

Solution would be either not to decode the body and return it intact, or (as hotfix) strip the Content-Encoding header

**Comment by klausbadelt** [comment]
#1309 fixed it but the fix was undone since in master. We're back to `accept-encoding: *` which triggers the bug flow as @ondrakoupil shows.

Why was the fix removed?

Our current workaround is to remove and middleware in development (in Rails: `config.middleware.delete Rack::Deflate` in `config/environments/development.rb`).

**Comment by slessard** [comment]
I just reproduced this problem with prism version 4.5.0. @klausbadelt suggested the fix was somehow reverted in master. @XVincentX Can this bug be reopened and the fix be reapplied to master?

**Comment by XVincentX** [comment]
@slessard I do not work for Stoplight anymore — I cannot help with this

**Comment by slessard** [comment]
@chohmann Can you help reopen this issue so that the (very simple) fix gets reapplied in the master branch?

**Comment by chohmann** [comment]
This was specifically removed as part of https://github.com/stoplightio/prism/pull/1319 so we'll have to take a look at why it was removed and what will happen if we add back the `compress` flag.

**Comment by radzserg** [comment]
The last fix that @XVincentX did 
```
return fetch(url, {
            body,
            method: input.method,
            headers: defaults(omit(input.headers, ['host']), {
              'accept-encoding': '*',
               ... 
            }),
          });
```
makes server return decompressed results. But at the same time, we send back `content-encoding: br`. 

```
➜  prism git:(master) ✗ curl --location --request GET 'http://127.0.0.1:4014/api/users/2' --header "Accept-Encoding: gzip, deflate, br" --header "Accept: */*" --verbose
Note: Unnecessary use of -X or --request, GET is already inferred.
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 4014 (#0)
> GET /api/users/2 HTTP/1.1
> Host: 127.0.0.1:4014
> Accept-Encoding: gzip, deflate, br
> Accept: */*
>
...
< content-type: application/json; charset=utf-8
....


< Content-Length: 280
< content-encoding: br

<
* Connection #0 to host 127.0.0.1 left intact
{"data":{"id":2,"email":"janet.weaver@reqres.in","first_name":"Janet","last_name":"Weaver","avatar":"https://reqres.in/img/faces/2-image.jpg"},"support":{"url":"https://reqres.in/#support-heading","text":"To keep ReqRes free, contributions towards server costs are appreciated!"}}* Closing connection 0
```

That causes 
`Error: Decompression failed` in Postman. Since Postman tries to decompress content again.

<img width="1242" alt="Screenshot 2021-11-19 at 12 26 55" src="https://user-images.githubusercontent.com/293785/142599596-89b0f1de-577f-46b5-a72a-870a98da5f74.png">

A fix that we can do, wipe `content-encoding` from the response headers.
