### ISSUE TITLE
Prismcli support for HTTPS 

### ISSUE THREAD

**Issue by HemTech** [stoplightio/prism#1090]
We have moved from http to https and found an issue with my mock data server. It is not supporting https. 
We are using prismcli which has option for port number and host name configuration. we did not find an option to provide https using prismcli.
Do we need to create proxy or have any option with prismcli command?

**Comment by XVincentX** [comment]
Hey @HemTech 

there is no support for HTTPS at this time and we do not plan to support it. It's really too complicated, it will not really add a lot of value in development environment and I would expect a lot of issues coming from people because of self signed certificates.

Moreover, there are a lot of really easy drop solutions that you can use to do TLS termination easily (and likely more efficiently). CaddyServer or Traefik is likely what you are looking for.
