### ISSUE TITLE
Referential integrity in dynamic mocks

### ISSUE THREAD

**Issue by jedateach** [stoplightio/prism#1224]
**User story.**
As a developer, I can define relationships between dynamic data, so that I can produce mocks that exercise more than a single model.

**Is your feature request related to a problem?**

I make use of the JSONAPI spec: (https://jsonapi.org), which is a very flat structure, which uses IDs to create relationships between models, which can sometimes be "included" (side-loaded) in a single call.

Apparently json-schema-faker has the concept of jsonPath to hook up references, but I wasn't able to get this working.

**Describe the solution you'd like**

I'd like dynamic mocks that produce JSONAPI data with valid references.

**Additional context**

This may have cross over with plans for persistence. I don't think jsonPath would be a viable solution across multiple API calls where data should be related.

**Comment by XVincentX** [comment]
Hey @jedateach — what you're asking looks interesting, and it might make sense in Prism.

I would need to get more details though; could you construct an hypothetical OAS2/3 document and show me what a response to a particular request would look like?

**Comment by taras** [comment]
I came here looking for the same. There is precedent for this. An obvious one is [Mirage.js](https://miragejs.com/) which is effectively an ORM behind an in-browser server. [Frontside team](https://github.com/thefrontside/) created a data store that we use to simulate a GraphQL server which provides us referential transparency for queries and mutations. We created it to allow us to create high fidelity simulations of a GraphQL schema that is not yet available. We would like to do the same thing with OpenAPI. 

This is easier to do with systems that have a concept of a model. Mirage.js for example has [models](https://miragejs.com/docs/main-concepts/models/) and [factories](https://miragejs.com/docs/main-concepts/factories/) which allows to create a simulated server by creating handlers that mutate in memory data store. The ORM allows to express relationships which can be used to construct complex data graph which is serialized to response payload. This is necessary for JSONAPI spec.

I'm guessing that it would be possible to wire Mirage ORM behind Prism but it wouldn't be my first choice for a long term solution. There is quite a bit of overhead to maintaining the Mirage simulator because it treats models and factories as separate things. Mirage's APIs for creating related data require quiet a bit of wiring. 

The Frontside team previously created an immutable in-memory data store with referential transparency and self materializing relationships using [Microstates.js](https://github.com/microstates). There might be a spike someplace. 

We're going to continue thinking about this and looking for opportunities to create a high fidelity simulator. I would love to contribute this work to Prism if you're interested in collaborating.

**Comment by philsturgeon** [comment]
Hey @taras, that's an interesting idea. I'm familiar with Mirage, and we're trying to avoid some of the trouble they've been having, where they basically built so much functionality people regularly ask if they can deploy their mock to production. Prism is more of a mock than a sandbox/simulation, but taking that next step is something we've always had in mind. 

If anyone interested in persistence could please vote for it [on the roadmap](https://roadmap.stoplight.io/c/50-persisted-mock-data), or discuss it more over on discussions (#962) we can try to limit the sprawl of the topics as they're historically spread all over the place. 

Thank you!

**Comment by taras** [comment]
@philsturgeon thanks for getting back to me. We actually created an alternative to Mirage's ORM that doesn't require managing relationships - it automatically takes care of constructing a stable [graph of data](https://github.com/thefrontside/graphgen). If you become interested in expanding the scope of Prism mocking to allow simulation, I'll be happy to show you GraphGen in action.
