### ISSUE TITLE
Proxy behaves like mock when upstream returns 501, proxy otherwise

### ISSUE THREAD

**Issue by sandinmyjoints** [stoplightio/prism#1273]
## User story.

As a dev, I can do run proxy getting real values from upstream when a route has been implemented upstream, and mocked values when a route has not been implemented upstream, so that I can get the best of both worlds.

## Is your feature request related to a problem?

I'd like to get real data as soon as it's available, but also continue to get mocked data for routes that are not yet implemented.

## Describe the solution you'd like

When upstream returns 501 (not implemented), prism behaves as it does in mock mode. Else, it behaves as in proxy mode.

**Comment by XVincentX** [comment]
This seems a very reasonable feature @sandinmyjoints and its implementation should not be that hard at all. 

This used to be a thing in Prism v2, it might be worth to implement back in v3 as well. @philsturgeon what do you think?

**Comment by XVincentX** [comment]
I’ve been thinking how difficult would be to implement such feature.

Well, in a regular flow, we would probably need to catch the exception when the request fails and if so, reissue the request to use the mocker and return the data to the user. I can’t really speak how such implementation would look like, but I would say the chances of leaking logic in the proxy is kind of high.

Oh, it turns out we’re using fp-ts and in such case, the implementation is literally 4 lines of code. Job done, works out of the box.

```diff
- components.forward(config, upstream);
+ pipe(
+   components.forward(config, upstream),
+   TE.orElse(error =>
+     error.code === 501
+       ? TE.fromEither(components.mock(configObject))
+       : TE.left(error)
+   )
+ )
```

**Comment by philsturgeon** [comment]
Looking at the use case provided in the issue, I wonder if this is too specific for the general case.

For a lot of people, if they've defined `/a` and `/b` but somebody calls `/c`, in most web application frameworks I know they'll just get a 404 not a 501. 

How are you controlling the 501s? Are you defining them in your codebase, or something else?

**Comment by sandinmyjoints** [comment]
Yup, my team controls the server, so I was envisioning that we'd define the api routes we know we'll be creating to do nothing but return 501, so we can continue to focus on front-end development and get mocked data for these routes, yet get real data for the (many) already existing api routes. Later we'll implement the 501 routes for real.

For a team that doesn't control the server to use this feature, they'd need to coordinate with whoever does control the server (which needs to happen anyway, or they're never launching 😄 ). But if they can't or don't want to do that, then they can just keep using prism the way it is now, which is already pretty good!

**Comment by philsturgeon** [comment]
Gotcha.

So, in Prism v2 there were a lot of different ways you could make mock be a proxy or proxy be a mock, and the general feedback was that it was all rather confusing. 

We've always intended to bring back "proxy what is done and mock what is not", or "mock the slow bits proxy the rest" or other types of scenario, and now might be a good time to have a discussion about that.

I'd rather avoid lots of piecemeal little exceptions like this, and see if we can create a generic way to handle "when proxy should be a mock". We've so far managed to avoid having a config file (#417) in prism and I'd hope we can continue to avoid that.

So, does anyone have any tips or ideas for how we can create generic functionality in Prism that will allow people to decide that certain known requests, or certain responses, should be mocked instead of proxied, that isn't just checking for 501?

**Comment by sandinmyjoints** [comment]
We introduced a convention of including a magic string ("mocked") in the summary field of the openapi definitions of our endpoints that aren't implemented yet to hang a regex off of when running Dredd and thereby skip testing them. Perhaps a similar technique could work here? I don't too much about openapi but I see it includes a tags field -- my recollection is that this was ignored by Dredd's hooks but maybe prism could check for the presence of a `mocked` tag to decide whether to mock or proxy.

**Comment by XVincentX** [comment]
@philsturgeon Maybe we could put that in the Prefer header?

**Comment by philsturgeon** [comment]
@XVincentX what are you thinking the option would be? Maybe mockOnError=true or mockOnServerError to be more specific?

**Comment by XVincentX** [comment]
`mockOnNotImplemented`?

**Comment by philsturgeon** [comment]
Ok, that does take us back to demanding API implementers implement 501 and not have it just 404 (as most frameworks do by default) which kinda seems like a very narrow use case to me.

Maybe it’s fine, we’re just teaching folks to “reserve” endpoints for upcoming functionality?

**Comment by XVincentX** [comment]
That is a fair concern; 404 is default, 501 is usually returned on purpose (requiring likely user code). I guess we can probably make that happen on 404 as well when the flag is on

**Comment by philsturgeon** [comment]
Right buuuut a 404 could mean /foo doesnt exist or could mean /foo/456 does not exist, so if you call up a record which doesn't exist you might _want_ that 404 instead of getting a mock. A setting wouldn't help because you might want /not-done-yet to be mocked but still expect /implemented/just-deleted-id to 404, so... 

I'm not trying to be difficult, im trying to figure out how to productize this in a way thats useful for most people without making them jump through hoops they might not know about. 

If we really want to focus on 501 we need to change how people code their APIs in order to get the mock tool to do what they want, and that might be a big ask.

@marbemac I'd be interested in your input here. :)

**Comment by sandinmyjoints** [comment]
My $0.02 (as someone outside your company, so I don't know exactly what your idea of your userbase is): 
- as an opt-in feature, this doesn't *force* anyone to jump through any hoops -- it's strictly additive to what you've got
- totally agree that "real" 404s, say for records that don't exist, should still be 404s -- can't break that behavior
- implementing 501 can be super simple, for us it's really just `app.get('/new-feature', (req, res) => res.sendStatus(501))`. Obviously every app/repo is different, and I can imagine situations in which a team using prism is unable to do that, like if they don't have control over the backend -- this feature probably isn't going to work out for them. But for small teams like ours who control front and backend, this could be super useful. We just added apis for essentially a new product onto an existing app, and we were able to mostly do the front-end first thanks for prism, and that was very helpful since we got feedback that informed changes to our models and APIs, and since they hadn't really been implemented yet, it was much less costly to change them! BUT there was a limit to what we could do here b/c we can't mix responses of real data from the existing endpoints with mock data from the new endpoints, so we could not roll out prism into a staging environment where non-engineering stakeholders could get hands-on with the features. Being able to do that would have been incredibly more valuable. 

I'm not wedded to 501 as the way to do it, but somehow having this passthrough functionality would have been a big win for us, and I'd love to be able to use something like it on our next big feature!

**Comment by sandinmyjoints** [comment]
And fwiw, if the route is `/new-feature/:id`, I'd be fine with that never returning 404 and always returning 501, since a) we don't care nearly as much about exercising not-found cases as found cases and b) if we really want to exercise not-found, I think we could write a not found example and use `Prefer: example=notFound`.

**Comment by philsturgeon** [comment]
Alright, this has had some time to bounce around my brain and it's honestly a very simple convention to recommend to people that doesn't involve much heavy lifting on our side or their side. 

We can easily make some documentation suggesting people slap a `app.get('/new-feature', (req, res) => res.sendStatus(501))` in their codebase to help guide proxy towards the mock, and this solves the "how to combine mocks and proxies" nicely without making Prism super confusing.

@XVincentX think this can get squeezed into an upcoming sprint seeing as you've got some of the code there already? Just needs some testing and maybe getting shoved into a beta build for @sandinmyjoints to play with?

**Comment by XVincentX** [comment]
Absolutely. It's going to take more time to write the docs for this rather than implementing the feature itself.

Scheduled for the next sprint.

**Comment by XVincentX** [comment]
Hey @sandinmyjoints,

I have prepared a PR that should be implementing the feature you're looking for. Would you mind cloning down the branch, try that out and let us know if that fulfils your request?

Cheers!

**Comment by sandinmyjoints** [comment]
Thanks @XVincentX ! I will try to get to this and get back to you soon. We have an opportunity coming down the pipeline where this will be really useful.

**Comment by XVincentX** [comment]
Sweet. @sandinmyjoints we haven't released this yet (although it's merged), so you're going to have to work from the master branch's source code.

**Comment by sandinmyjoints** [comment]
I had a chance to try this out, and it worked great! Thanks!
