### ISSUE TITLE
Allow for turning off case-sensitivity when checking headers, query parameters, and body properties

### ISSUE THREAD

**Issue by TylerNielsen** [stoplightio/prism#1284]
## User story.

As a developer or QAer, I can tell my prism mock or proxy server to be case-insensitive for parameters, body properties, and headers, so that mock servers can behave similarly to http libraries that do not care about casing.

## Is your feature request related to a problem?

Many libraries, such as Node's Express library, are not case sensitive for headers, query parameters, and body properties. Additionally, depending on the client library used to interact with an api, default serialization may use title case or camel case. We're running into the case where we code generate our client SDK, which is using different casing from the OpenApi spec. This causes our mock server to reject all of the requests from our front-end because the casing is wrong, even though our actual API would have accepted it. 

## Describe the solution you'd like

Would like a --case-insensitive flag available for the prism mock and prism proxy commands that will ignore case when evaluating headers, query parameters, and body properties.

**Comment by XVincentX** [comment]
Can you provide an example? The thing is that we want to be close to the standard as much as possible and, for example, headers and query parameters are case-insensitive while body parameters are content-type specific.

An example would help yo understand what's the part you're having the issue with

**Comment by TylerNielsen** [comment]
Hey Vincent, my request was overly broad. My use case is that our API implementation is not sensitive to the casing of json body properties. 

 { "myString" : "value" } = { "MyString" : "value" }

I was using prism to mock services for the UI, but was getting errors since the client code was serializing the json to be camelCase instead of PascalCase. With the live service, either would have been fine.

**Comment by XVincentX** [comment]
Ah ok now I understand. Hmm…

> API implementation is not sensitive to the casing of json body properties.

Ok, this looks like against the standard since JSON is case sensitive — and so are the parsed properties. 

If I understand correctly your previous message, this is not a feature we can put in Prism, since it seems like the "problem" is in your implementation; Prism is doing what it should do.

Can't you change the JSON Schema associated with the OpenAPI document to have the properties correctly spelled?

**Comment by aufero-system** [comment]
Hey @XVincentX - totally can appreciate that it's against the formal specification since json should be case sensitive, but pragmatically, there are libraries where they can interpret an incoming body property like "ClientId" as matching expected body property of "clientId". Since we use one of these frameworks, and don't have a compelling reason to change this behavior, we were hoping there would be a way to have the proxy/mock work as our implementation does. 

If it doesn't seem it makes sense to implement something like this into Prism (I can appreciate why you might not want to), we will just have to make sure our internally used tools/clients/UIs convert to use the casing specified.
