### ISSUE TITLE
not able to run prism command from node_modules/.bin

### ISSUE THREAD

**Issue by ram-potla** [stoplightio/prism#1407]
## Describe the bug
First time I have installed it through Package.json . Tried running prism --help or any prism commands I am seeing below error. 
Error: No valid exports main found for

internal/modules/cjs/loader.js:621
  throw e;
  ^

## To Reproduce

node version 13.3.0 
installed @spotlight/prism-cli
run any prism command

## Additional context
Not able to run any prism commands. Can't even run prism --help

**Screenshots**

**Environment :**
  "@stoplight/prism-cli": "^4.0.1",
    "typescript": "^4.0.2"

Mac Mojave
node : v13.3.0

**Comment by XVincentX** [comment]
@ram-potla 

I cannot reproduce the issue

<img width="955" alt="image" src="https://user-images.githubusercontent.com/1416224/92594970-edb6e980-f2a3-11ea-98aa-0b8649394771.png">


In any case, can you elaborate on what's your use case? The CLI is not meant to be installed as a dependency or if you need to, run it using `npx` instead of running it by calling it directly.

Feel free to reopen when you have more details.

**Comment by ram-potla** [comment]
Thank you for your response. 
I have updated node version from 13.3.0 to 14.10.0. It's all fine. For some reason couldn't run with v13.3.0
