### ISSUE TITLE
SIGSEGV on Debian

### ISSUE THREAD

**Issue by 7hibault** [stoplightio/prism#142]
# Subject of the issue
I get a segfault when I try to run prism on Debian/buster.

# The issue

## The environment

* prism was installed with the install.sh script, with some changes to it to allow the install when there are spaces in the path (cf PR https://github.com/stoplightio/prism/pull/134). Maybe I've done something wrong here.
* debian buster (testing)

## Steps to reproduce

* install prism with the above script on debian 
* run `prism run --mock --list --spec http://petstore.swagger.io/v2/swagger.json`

## Expected behaviour

* prism should run the mock server

## Actual behaviour

* prism fails with a segfault
```
fatal error: unexpected signal during runtime execution                                                                                  
[signal SIGSEGV: segmentation violation code=0x1 addr=0xffffffffff600000 pc=0xffffffffff600000]        
```

**Comment by ntiss** [comment]
According to your commandline, it looks like you are using an old version of prism because of the `run` option. Probably 0.6.21 or previous.

I tried with Prism 2.0.0.-beta.9-6 with this command : `prism mock --spec http://petstore.swagger.io/v2/swagger.json`
The mock works fine if I send requests with `wget -qO- http://localhost:4010/pet/123`
Successfully tested on Ubuntu 16.04 LTS and CentOS 7.3.1611 (Core).

Hoping it can help.

(Btw, not sure that the install.sh is still working because Github responds "API rate limit exceeded" when I request  with `curl -s https://api.github.com/repos/stoplightio/prism/tags`)

**Comment by 7hibault** [comment]
Hi,

Thanks to your help, I managed to run prism after upgrading it. It seems to be working fine now :)

A few notes on that:

* I used the [install and run instructions on the homepage](http://stoplight.io/platform/prism/). This is the [same as what's in the doc](https://help.stoplight.io/prism/getting-started/prism-introduction?utm_source=github&utm_medium=prism). Either the install instruction or the install script location should probably be updated.
```
RUN IT
1) curl https://raw.githubusercontent.com/stoplightio/prism/master/install.sh | sh
2) prism run --mock --list --spec http://petstore.swagger.io/v2/swagger.json
```
* Then I used the install instructions on the README `curl https://raw.githubusercontent.com/stoplightio/prism/2.x/install.sh | sh`. This still wasn't the right version, as it didn't know the mock option. I had to upgrade it after.

**Comment by ntiss** [comment]
Yes, you're right.

The Github API URL used in install.sh (https://api.github.com/repos/stoplightio/prism/tags) doesn't sort the tags in the right order : "v2.0.0-beta.9" comes first instead of "v2.0.0-beta.9-6". It's alphabetically sorted. And there is no option to sort the response of the API with `?sort=created` : 
 - Doc of API v3 : https://developer.github.com/v3/repos/#list-tags
 - Issue on Stackoverflow : https://stackoverflow.com/questions/19452244/github-api-v3-order-tags-by-creation-date

A workaround could be to use this url : https://api.github.com/repos/stoplightio/prism/releases or to forge a GraphQL query.

@pytlesk4  😉

**Comment by pytlesk4** [comment]
Bumping Prism to 2.0.0 today, which should fix this issue. I have to admit that the versioning we were using is a bit weird. There was a issue with the prism update command and the way we were parsing version: https://github.com/hashicorp/go-version/issues/32 which has been fixed.

@ntiss thanks for the info going to look into!

**Comment by pytlesk4** [comment]
Going to close this, going to go back to normal semantic versioning.
