### ISSUE TITLE
Is it possible to generate JSON Schema draft07 dynamically or maybe defining the mock response by ourselves?

### ISSUE THREAD

**Issue by mochadwi** [stoplightio/prism#1427]
## User story.

As an android dev, I can do parsing a JSON Schema, so that I can render views dynamically in android.

## Is your feature request related to a problem?

Waiting for request / response documentation sometimes takes a while, thus our current approach (android team) always building an APIARY mock api to dynamically set a request/response JSON.

## Describe the solution you'd like

The JSON Schema generator based on pre-defined type properties or maybe generate a mock response pre-defined by ourselves, e.g: manually putting the JSON request/response in our own

## Additional context

<none>

**Comment by philsturgeon** [comment]
Hey, I don't understand what you mean.

Prism runs off a OpenAPI YAML, and it does not matter who creates that file. If your backend team are slow at making them (because they're not doing design first) then you can make your own. This is consumer-driven mocking, and you can do it with OpenAPI by designing the API you'd LIKE to use and sharing that OpenAPI contract with the backend team so they know what to build.

If you just want to shove any old JSON into a HTTP Server there's a lot of ways of doing that, including [typicode/json-server](https://github.com/typicode/json-server).
