### ISSUE TITLE
when i  use the mock option it always return random response ,how can it return the example in swagger.json file

### ISSUE THREAD

**Issue by lzbpythoner** [stoplightio/prism#143]

**Comment by kliyes** [comment]
Same here, even if I set mock.dynamic: false

**Comment by kliyes** [comment]
I figured it out with @pytlesk4 answered in #111 
You should use `examples` definition in `responses`([spec](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#response-object)) rather than `example` in `schema` ([spec](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#fixed-fields-13)), and set 
```
x-stoplight:
    mock:
      enable: true
      dynamic: false
```
in swagger specification.
Then if defined `examples` in `responses`, it will return example response, the otherwise dynamic response returned.

**Comment by pytlesk4** [comment]
@lzbpythoner could you provide a little bit more information? 

- What version of prism are you using?
- Can you share your spec file?
- What is the command you using?
