### ISSUE TITLE
"Access Denied" message during running prism validate on mock server

### ISSUE THREAD

**Issue by amalsgit** [stoplightio/prism#151]
I created a mock server as shown below:
`C:\Users\ajayara\Downloads\prism>prism_windows_386.exe  mock --spec C:\Project\bitbucket_new\mypath\MyService.oas2.yml`

`Prism version is 2.0.12`
`Prism mock server started on port 4010`

Now when I run prism validate to perform contract test, I get the error "access denied"
`C:\windows\system32>C:\Users\ajayara\Downloads\prism>prism_windows_386.exe validate --spec C:\Project\bitbucket_new\mypath\MyService.oas2.yml --upstream http://localhost:4010`

`Access is denied.`

My Prism version is 2.0.12 and I am running this on a windows 10 machine.
Am I missing anything in the way I execute the commands?

**Comment by pytlesk4** [comment]
@amalsgit are you running the mock server at the same time you are running the validate server? If you are it looks like you want to send requests through the validate server to the mock server? If that is the case, you actually don't need to run the validate server, when you mock your specification with the mock command, your request/response headers/body will be contract tested. 

The response will have up to 4 headers on it Sl-Request-Valid, Sl-Request-Validation-Messages, Sl-Response-Valid, Sl-Response-Validation-Messages.

- Sl-Request-Valid: can 'true' or 'false'. If it is false, then Sl-Request-Validation-Messages will be a stringified array of objects and each object is a validation error. If Sl-Request-Valid isn't set, it means validation wasn't run because nothing was defined in your specification.

- Sl-Response-Valid: samething as the request headers, but just for the response.

Just to clarify what is happening when you run the mock server, and then the validate server, prism by default starts a server on 4010, so in if you update your validate command with -p 4011, then when you send a request through localhost:4011, if will be forward to your mock server.
