### ISSUE TITLE
Shouldn't headers be of typed as Record<string, string | string [] | undefined>?

### ISSUE THREAD

**Issue by nulltoken** [stoplightio/prism#1552]
## Describe the bug

More a question than a bug.

Nodejs `IncomingHttpHeaders` are typed as `Record<string, string | string [] | undefined>` to cope with potentially repeated headers

https://github.com/stoplightio/prism/blob/master/packages/http-server/src/server.ts#L77 cast incoming headers as `IHttpNameValue` (which is `Record<string, string>`).

https://github.com/stoplightio/prism/blob/master/packages/http/src/types.ts#L32-L37 define `IHttpRequest.headers` and `IHttpResponse.headers` as `IHttpNameValue`

Shouldn't they rather be `Dictionary<string | string[] | undefined>`?

**Comment by XVincentX** [comment]
You're right, and we've been speaking about this already couple of times.

The problem is — changing this type in the package would probably just be fine in Prism; unfortunately it's going to break half of Stoplight, so its change must be a little bit more coordinated than it seems.

I'm not against this — I'm actually all for it, but it must be "orchestrated", put it that way.
