### ISSUE TITLE
prism proxy should mock on 404, not (or in addition to) 501

### ISSUE THREAD

**Issue by klausbadelt** [stoplightio/prism#1862]
## Summary

Change or add 404 to the list of upstream status codes `prism proxy` re-mocks on.

## Tasks

- [ ] PR to add 404 to the list - or -
- [ ] PR to add a configuration option (as described below)

## Additional context

`prism proxy` "re-mocks" when it receives 501 from upstream. But "501 is the appropriate response when the server does not recognize the request [_method_](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/501)" (MDN).

`prism proxy`, however, should re-mock when "the server can't find the requested [_resource_](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/404)" (MDN). This should be indicated by a 404.

Also, most frameworks today respond with a 404 on a missing route/endpoint (NextJS, Rails) out of the box. Using 501 requires custom code.

I therefore suggest to either
1. replace 501 with 404 for re-mocking (breaking change)
1. add 404 to the list of re-mocked status codes
1. add configuration which port to use, for example `-c, --upstream-code [number] [default: 501]`. 

## PR

If you would entertain this idea, we'd consider writing a PR.

**Comment by klausbadelt** [comment]
A simple solution could be for prism to respond with the same code it received from the API if it can't find the endpoint to remock. 

For example, 

* prism proxies a request
* downstream api responds with 501 (or 404)
* it doesn't find an endpoint to remock
* it responds with 501 or 404

Point is, as virtually no API commonly responds with 501 on not-yet-implemented endpoints, we'd have to implement 501 responses temporarily in the API, and replace the, later with the real response. Kinda nuts. 😀

**Comment by philsturgeon** [comment]
> we'd have to implement 501 responses temporarily in the API, and replace the, later with the real response.

I'm not sure if you've ever seen this happen, but before mocking tools like Prism people were coding up the routes and controllers, then returning static objects/arrays of JSON.

Adding `res.status(501).send()` until you're finished getting feedback on the mock then writing then replacing it with code seems ok. I'd rather ask people to opt in to mocks than have mocks pop up unexpected on fully functional endpoints just because you requested a missing item from a collection. That's just spooky and confusing. 

If there is another approach to mixing mock+proxy then let me know, I've been trying to find nice solutions to this for ages and settled on 501 as a partial way there, but I'm not sure auto-mock 404s is the next step. Let's see if we can come up with something else?

**Comment by chohmann** [comment]
Hi @klausbadelt our team decided that this feature is not one that we want to support in Prism. If you have any other ideas around this topic, feel free to re-open, but for now, we're going to close this request. Thank you!

**Comment by saturna** [comment]
That's too bad. My team was looking for the exact same functionality. Although the proposed solution would potentially open up doors to ambiguities, it would be nice if we could let individual teams decide how they would like to use this tool. This could be an advanced config parameter such as re-mock-on=[404, 501, ...]
