### ISSUE TITLE
Heap out of memory / slow responses for dynamic response generation

### ISSUE THREAD

**Issue by gunnartorfis** [stoplightio/prism#1926]
## Describe the bug
I'm using Prism as a mock server for our OpenAPI spec. 
The default configuration works flawlessly but once I add the -d flag, the response either takes up to a minute or the mock server crashes with the stacktrace listed under the **screenshots** section. 

## To Reproduce
1. I was hoping I could not share our OpenAPI spec just yet in case there is something obvious that I'm missing. If not, I will update the issue.
2. prism mock -d spec.yaml
3. See error

## Expected behavior
The response should generate faker data dynamically with a fraction of the current memory/response time. 

**Screenshots**
<img width="1378" alt="image" src="https://user-images.githubusercontent.com/5333875/138447114-4af48622-3e3e-4e39-b6d9-fd1ac03f8dc1.png">

**Environment (remove any that are not applicable):**
 - Library version: 4.4.2
 - macOS Big Sur
 - Macbook Pro M1
 - CLI

**Comment by EdVinyard** [comment]
@gunnartorfis, rather than a reference cycle, I think the out-of-memory errors are likely caused by the arrays, nested 3 levels deep, in the original spec.

If I restrict the number of dynamically generated array items json-schema-faker will generate, I can reliably get a prompt response.  We recently added the ability to do this in [v4.5.0](https://github.com/stoplightio/prism/releases/tag/v4.5.0).  At the top of your specification, I added [a json-schema-faker directive](https://github.com/json-schema-faker/json-schema-faker/tree/master/docs#available-options) like this:

```yaml
openapi: 3.0.2
x-json-schema-faker:
  maxItems: 2
# ...
```

Experimenting with a few different sizes, it's easy to see that dynamically generated response grow large quickly:

| maxItems | smallest response (KB) | largest response (KB) |
|--|--|--|
| 2 | 10 | 55 |
| 3 | 42 | 430 |
| 4 | 127 | 2200 |

Would adding a `x-json-schema-faker` directive be a satisfactory solution to this problem?  Please let me know if I've missed something, or if that solution won't work.

**Comment by gunnartorfis** [comment]
Thank you so much for the reply @EdVinyard and giving you the time to help me. 

I upgraded the Prism CLI to 4.5 and added x-json-schema-faker. It works like a charm 👏👏
