### ISSUE TITLE
x-faker attributes not applied

### ISSUE THREAD

**Issue by InfoSec812** [stoplightio/prism#1965]
## Describe the bug

I have added an `x-json-schema-faker` block to the top-level of my OpenAPI 3.0.2 specification and I have added `x-faker` attributes
to some of my fields, but those attributes are not changing the returned data from prism

## To Reproduce

1. Given [this OpenAPI document](https://raw.githubusercontent.com/redhat-appdev-practice/quasar-openapi-pinia/main/openapi.yml)
2. Run this CLI command `prism mock -d --cors -p 7080 openapi.yml`
3. Make a request to `http://localhost:7080/todos`
4. Note that the `due_date` and `completed` fields often have dates from several decades earlier even though the `x-faker` settings specify `date.soon` or `date.recent`.
5. Note that the `title` field is still returning lorem ipsum content instead of `internet.username`

## Expected behavior

* I would expect that the `due_date` would be sometime in the future
* I would expect the `completed` to be a date in the recent past
* I would expect the `title` to be something other than lorem ipsum content

## Additional context
None

**Screenshots**

![image](https://user-images.githubusercontent.com/99691/146710223-27d0d54b-84e5-479b-8359-a8a7819a8a4e.png)

**Environment (remove any that are not applicable):**
 - Library version: 4.6.1
 - OS: Linux/Xubuntu 21.10
 - Browser: N/A
 - Platform: Desktop
 - NodeJS: v14.18.1

**Comment by InfoSec812** [comment]
I have started a branch on my fork to try to figure out why it's not working, but so far no luck:

https://github.com/InfoSec812/prism/tree/fix/1965-_-Fix_xFaker_issue

**Comment by InfoSec812** [comment]
OK, debugging and tracing through I see that the schema is being passed correctly to the `jsf.generate` function, but it is still not applying the correct fake data.

**Comment by EdVinyard** [comment]
@InfoSec812 , since you originally asked about this, we've [added some Prism documentation with simple examples](https://meta.stoplight.io/docs/prism/83dbbd75532cf-http-mocking#dynamic-response-generation) and [this comment on another issue](https://github.com/stoplightio/prism/pull/2012#issue-1166956104) includes a little more detail.

Here's how to make x-faker work for one of the specific properties in your example YAML:

```yaml
        title:
          type: string
          x-faker: 
            internet.userName:
          maxLength: 255
```

yields something like

```json
"title": "Jabari_Stamm",
```

All that said, there's definitely a problem for some (all?) of the date-time related fakes.  As an example, the following 

```yaml
        due_date:
          type: string
          x-faker: 
            date.past:
```

yields

```json
"due_date": "Tue Sep 14 2021 05:34:08 GMT-0500 (Central Daylight Time)",
```

I've opened https://github.com/stoplightio/prism/issues/2056 to address the specific Faker options we know of that either don't work at all, or as expected.

**Comment by InfoSec812** [comment]
Thanks for your help!
