### ISSUE TITLE
Multiple API files as input for prism mock

### ISSUE THREAD

**Issue by DeepthiDinesh** [stoplightio/prism#2002]
With the current set up we are able to pass only a single Swagger or Open API file as input to generate mock responses and start the mock server. Is it possible to provide multiple files in <document> and prism can generate mock responses for multiple files?

prism mock <document>

**Comment by tommie822** [comment]
I would like this feature as well, currently the only way to serve multiple files is by using a docker compose as is demonstrated in the [documentation](https://meta.stoplight.io/docs/prism/ZG9jOjE2MDY1Njcx-serving-multiple-open-api-documents).

If multiple files could be served with one server, this would make the scenario of publishing a mock server from a pipeline easier.

**Comment by chohmann** [comment]
The challenge we see with the feature is, how do you handle if there are conflicts between the different specs? (i.e. same path, operation, how to route traffic, etc.)

The documentation is intended to provide ideas and concepts for how to handle multiple files. For example, instead of using docker + caddy as documented, you could use any http proxy + any process management tool to achieve the same results. We will look at getting the documentation updated to reflect that there are multiple ways to achieve this.

I'm going to assign this ticket to our technical doc writer.
