### ISSUE TITLE
Not required query params are not validated

### ISSUE THREAD

**Issue by mtsivyna** [stoplightio/prism#2187]
Query params are not validated if there are not required ("required": true)

## Steps to Reproduce

> "/endpoint": {
>       "get": {
>         "tags": [
>           "some_tag"
>         ],
>         "summary": "Get something",
>         "description": "",
>         "parameters": [
>           {
>             "required": false,
>             "schema": {
>               "title": "Paramid",
>               "type": "string",
>               "format": "uuid"
>             },
>             "name": "paramid",
>             "in": "query"
>           },

Usage in test # 1:
`    get_resp = await app_client.get("/endpoint",
        params={"paramid": str(uid())})`
returns: 200 OK

Usage in test # 2:
`    get_resp = await app_client.get("/endpoint",
        params={"incorrect_parameter_name": str(uid())})`
returns: 200 OK

**Expected behavior**

Get a validation error in response.

**Actual**

I get the correct JSON object and OK status

**Environment (remove any that are not applicable):**
 - Library version: 4.10.3

**Comment by chohmann** [comment]
@mtsivyna this is working correctly. Your spec has the query param `paramid` as not required so it's not an error that you didn't supply it, since it's not required. It's also not an error to provide an additional parameter as there is no property in OpenAPI that allows you to control whether or not additional parameters are allowed. Let us know if you have any other questions!
