### ISSUE TITLE
Serving Multiple OpenAPI Documents - Without any/differing prefixes?

### ISSUE THREAD

**Issue by goldingdamien** [stoplightio/prism#2438]
At the documentation link below, there is information regarding how to serve APIs from multiple openapi configs at once.
In the examples, a prefix is always added to the URL such as "app_1".
Is there a way to do this without adding any prefixes so that all APIs can start at the same base URL?

[Serving Multiple OpenAPI Documents](https://docs.stoplight.io/docs/prism/4bf78efbf9dd2-serving-multiple-open-api-documents)

**Comment by chohmann** [comment]
@goldingdamien in order to achieve what you're asking for based on the example provided in our docs, you'd have to play around with the caddy config. This wouldn't be something Prism itself would handle, and therefore, we don't have an exact solution for you. 

A potential other approach would be to find a tool that would combine the OpenAPI files into one, and then just only have one instance of Prism running serving that one OpenAPI file.
