### ISSUE TITLE
configurable concurrency

### ISSUE THREAD

**Issue by marbemac** [stoplightio/prism#25]
In some situations, it is not desirable to have all scenarios in a collection run concurrently.

Simplest configuration would be sequential versus parallel (what we have now).

**Comment by MissingHandle** [comment]
👍 on wanting concurrency controls.  I would not want to run everything sequentially, that would be painfully slow, but I would like to be able to configure number of concurrent requests, etc.

Along with this is a configurable request timeout where the scenario just fails if it is waiting longer than X seconds - in the current case, since I have many dropped requests (I believe b/c my dev server is being taken down by the number of concurrent requests), I only want to wait a few seconds (as opposed to right now having to wait 30 seconds) to find out results failed.

**Comment by marbemac** [comment]
@MissingHandle tracking the request timeout here #22 :)

**Comment by pytlesk4** [comment]
needed-by #71 
- should be able to define concurrency on the collection level and on the scenario level, which will take priority over the collection level concurrency setting.

**Comment by marbemac** [comment]
Additionally, sane defaults - something like 10 at the collection level, and 1 at the scenario level.

**Comment by pytlesk4** [comment]
- Also needs to be supported from the command line as well

**Comment by marbemac** [comment]
I would suggest that they can use an environment variable instead (and environment variables should support defaults). Then it would work like this:

```
{
  "config": {
    "concurrency": "{$$.env.concurrency}"
  },
  "scenarios": {
    "123": {
      "config": {
        "concurrency": "{$$.env.fastConcurrency}"
      }
    }
  }
}
```

With this way, they can come up with whatever concurrency schemes they like, configured however they like, and it uses our existing variables system.

Thoughts?

**Comment by marbemac** [comment]
With the above, we need (in code, not exposed as options to user) min/max concurrency for collection and scenario. This puts a cap on the allowed concurrency, so the user cannot choose 10000 on our hosted infrastructure.
