### ISSUE TITLE
Choosing between responses in a `oneOf` block

### ISSUE THREAD

**Issue by lornajane** [stoplightio/prism#298]
I have an OpenAPI spec that describes an old API that returns 200 responses always. Which fields are in there depend on whether it was successful, so the response section looks something like:

```
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/requestResponse'
                  - $ref: '#/components/schemas/requestErrorResponse'
```

It seems like Prism returns the last response it gets, which in this example isn't that useful because I'd quite like the successful request at least once in a while!

I'm using the `develop` branch and have renamed my `.yml` file to `.yaml` to do this test.

**Comment by philsturgeon** [comment]
This is a tricky one! 

When its different status codes, that's a simple one because you can invoke them with `?__code=418`. 

When it's different examples in a status code, you can invoke that with `?__example=lovely-teapot`. 

When it comes down to invoking a specific branch in a oneOf... that would be pretty tricky.

Do you think an acceptable workaround for now is to always take the first of a branch like this? So it would always be the success instead? 

You could then provide an example of the success and an example of the failure using response examples, then invoke those examples with `?example=success` or `?example=failure`.

**Comment by philsturgeon** [comment]
@lornajane did you have any thoughts on this?

**Comment by lornajane** [comment]
Hmm, I will try the examples workaround, it sounds like the best option right now. The API I have this for returns either one set of fields on sucess, or another on failure - but always a 200 OK. Currently we let the OpenAPI tooling generate the example responses but I could also create a full working example to help with that.

**Comment by philsturgeon** [comment]
Awesome! Let me know if you think up a feature out of this, but for now at least it sounds like you're ok.

The #319 PR should at least mean the first branch is selected too, which will be another partial solution.
