### ISSUE TITLE
Integration with webpack dev server

### ISSUE THREAD

**Issue by raphaelsoul** [stoplightio/prism#306]
Is there any programing usage example for integrating prism into webpack dev server?

**Comment by XVincentX** [comment]
Hey,

I'm afraid we do not really offer such option out of the box; however I know that web pack dev server has a proxy capability; you can easily use it to proxy the calls you would do to it (assuming it's your API) and move them to Prism. 

Points taken, I think we can probably write a FAQ section for it.

**Comment by tmkasun** [comment]
I too have the same requirement, 
I want to use `prism` in the integration test, so We already running webpack-dev-server to server the static files + proxy some requests, So it's easy for us if we can do the API mocking using the same webpack-dev-server rather than running 2 processes, one for dev-server and another one for stoplight prism.

I tried @XVincentX 's method and it worked , but still I need to run 2 process
```js
devServer: {
            open: !isTestBuild,
            openPage: 'publisher',
            inline: true,
            hotOnly: !isTestBuild,
            hot: true,
            publicPath: '/site/public/dist/'
            proxy: {
                '/api/am': {
                    target: 'http://localhost:4010',
                    pathRewrite: { '^/api/am/publisher/v2/': '' },
                    secure: false,
                },
            },
        },
```
