### ISSUE TITLE
Prism is not respecting the Accept header

### ISSUE THREAD

**Issue by guilleiguaran** [stoplightio/prism#332]
**Describe the bug**
I'm getting empty responses from Prism mock server.

**To Reproduce**

Using this example specification:
https://gist.github.com/guilleiguaran/3cb198f59f804acae754124c57304ef6

1. When I run this command: 
`prism mock openapi.yml`

2. Then make the following HTTP request: 
`curl -i -H "Accept: application/vnd.api+json" "http://127.0.0.1:4010/languages"`

3. Then I got this response:

```
HTTP/1.1 200 OK
content-type: text/plain
content-length: 0
Date: Fri, 31 May 2019 22:57:57 GMT
Connection: keep-alive
```

**Expected behavior**
I expect one response like the one displayed by redoc-cli for same endpoint:
```
{
  "data": [
    {
      "type": "language",
      "id": "1",
      "attributes": {
        "name": "english"
      }
    }
  ]
}
```

**Desktop (please complete the following information):**

- OS: macOS 10.14.4
- Prism Version: 3.0.0-alpha.11.
- Install method: yarn

**Comment by XVincentX** [comment]
Hey @guilleiguaran 

thanks a lot for the detailed issue.

I've looked into it and basically there are two issues in Prism we need to tackle in order to make this scenario work:

1. Prism is ignoring the `Accept` and instead checking the request's `Content-Type` header; moreover it will auto fallback to `application/json` when trying to find a content for your response (which is not present in the document). This is already tracked in #288 and we hope to be work on this soon. You can in theory workaround this limitation by doing `curl -i -H "Content-Type: application/vnd.api+json" "http://127.0.0.1:4010/languages"` instead of the original command you provided.
2. Unfortunately right now Prism does not have an intelligent fallback algorithm. Fundamentally, it's not able to understand that `application/vnd.api+json` can be serialised with the regular JSON Serialiser, making it throw an error. The only workaround, right now, is to modify your OpenAPI document and set the content types of the returned responses to `application/json` instead of `application/vnd.api+json`.

We're on it though, and we hope to fix these issues soon.
//cc @philsturgeon 

Hasta pronto!

**Comment by guilleiguaran** [comment]
@XVincentX thanks for working on this so quickly, I have a question: #333 fix both issues that you mentioned or just the first one?

**Comment by XVincentX** [comment]
@guilleiguaran Both!
