### ISSUE TITLE
bug: Docker prism network unreachable 

### ISSUE THREAD

**Issue by KillianH** [stoplightio/prism#375]
**Describe the bug**
Unable to query the prism mock server

**To Reproduce**
Given these following commands : 

`docker run -p 4010:4010 --name prism stoplight/prism:master mock https://raw.githack.com/OAI/OpenAPI-Specification/master/examples/v3.0/petstore-expanded.yaml`
`wget http://127.0.0.1:4010/pets`

I'm getting `HTTP request sent, awaiting response... Read error (Connection reset by peer) in headers.`

**Expected behavior**
A response 😢 

**Desktop (please complete the following information):**

- OS: Ubuntu 18.04.1 LTS
- Prism Version : Master
- Install method : docker

**Comment by philsturgeon** [comment]
Can you try using running prism inside docker with -h 0.0.0.0, then make sure you’re hitting docker on the correct IP?

**Comment by XVincentX** [comment]
Yeah that's likely the issue, Prism listens on localhost by default.

**Comment by KillianH** [comment]
Yep I didn't read the docs for the CLI, my bad :confounded:

**Comment by hardboiled** [comment]
Two questions:
1. Where specifically would the reader be expected to find an explicit *if using docker, run `mock -h 0.0.0.0`* notice?

I found this page in the [documentation](https://stoplight.io/p/docs/gh/stoplightio/prism/docs/getting-started/installation.md), but only after I ended up finding a stackoverflow post explaining how to resolve the symptom of unreachable hosts within containers and looking at the prism source code and finding `localhost` being used.

2. Is there a reason not to default to 0.0.0.0 instead of localhost when running inside the container?

**Comment by philsturgeon** [comment]
@hardboiled hey Daniel! How did you find out about the docker image if not in the documentation? We put the install instructions there so folks would find it, but if you can help us make this instruction more clear that'll help others in the future.

Aha you added an edit while I was writing! We have "For more installation options, see Getting Started > Installation" on the Dockerhub page and they are just using our normal README, so I don't think we can show different content there without changing the README everywhere?

2. We didn't want to muck around with the code in Prism just for docker, so hopefully another solution can be thought up. We _could_ shim prism in the PATH to be a wrapper which sends -h 0.0.0.0 but that seems a little invasive and could cause confusion for others how might want it running on a specific other host.

**Comment by philsturgeon** [comment]
@hardboiled Agggh so many edits, I coudln't keep up! Yes, we can add it to the FAQ. :)

**Comment by hardboiled** [comment]
Yeah sorry, I didn't expect such a fast response. You're lightning quick. I did scan through the dockerhub  readme after running the image, but the [installation](https://hub.docker.com/r/stoplight/prism/#installation) section threw me off.

```
Installation

npm install -g @stoplight/prism-cli

# OR

yarn global add @stoplight/prism-cli
```

I didn't understand why I'm yarn installing anything if it's a docker image. As such, I think that caused me to skip over the link that I gave above, even though it was embedded in there. In general, installation for a docker image is confusing to me since normally an image should contain everything needed to run the application. If it doesn't, then I sometimes see a docker-compose or volume mapping given as instructions, but that's rare.

Thanks for hearing me out.

**Comment by XVincentX** [comment]
@hardboiled That is correct. If you're using the docker image there's nothing else to do rather than mounting the file in the container and use it:

`docker run stoplightio/prism:3 mock -h https://file.com/file.yml 0.0.0.0`

**Comment by hardboiled** [comment]
@philsturgeon 
I added a PR [here](https://github.com/stoplightio/prism/pull/646) that just sets an environment variable to decide which default IP address to use if the host IP is unset. Let me know if you like it.

**Comment by reanimatedmanx** [comment]
Guys, let's stop wasting collective development hours. Fuckin' hell, I waste 2 hours, person B wastes another hour, and so on and so forth whenever Docker + Prism is involved. Can we make that `0.0.0.0` or `127.0.0.1` the default instead of a `localhost` string? Look at NextJS/NestJS they always use pure numerical representation of IPs. The error was so ambiguous and the solution so counter-intuitive that the only way I could solve it is basically finding this issue or wasting another 3+ hours to try and fix it solobolo. 

Let's have some basic respect. ❤️‍🔥
