### ISSUE TITLE
Add CORS Support

### ISSUE THREAD

**Issue by brianmrock** [stoplightio/prism#412]
**User Story**

As a frontend developer integrating my Prism HTTP instance with a browser-based application, I want to be able to configure CORS on Prism, so my browser doesn't complain about same origin policy failures, etc.

**ACs**
- [HTTP headers relating to CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#The_HTTP_response_headers) can be controlled via CLI flags / options
- add at least the following test harness scenarios described in the examples section

**Test Harness Scenarios**

CORS enabled 
- Access-Control-Allow-Origin equal to "*" or the domain Prism is running on matches Origin header sent from a client CORS request - a request made from one domain to another domain (Origin header and URL on different domains)

Given I run Prism v3 with --cors-enabled=false
When I send a CORS request to an operation
Then I should get a 401 response back

When I send a request to an endpoint
And Origin header in the request is the same domain as Prism
Then I should get back a 2xx response back

Given I run Prism v3 with --cors-enabled or I omit this flag

When I send a CORS request to an endpoint
And I don't include Origin header in the request
Then I should get a 400 response back

When I send a CORS request to an endpoint
And Origin header in the request is not in the same domain as Prism 
Then I should get back a 401 response

Given no Access-Control-Allow-Origin was configured for an operation
When I send a request to this operation
And Origin header is not in the same domain as Prism
Then Prism should response with a 401 status code
And there should be no Access-Control-Allow-Origin in the response

Given an operation is configured to answer with Access-Control-Expose-Headers header
When I send a request to this operation
Then Access-Control-Expose-Headers should be included in the response

Given an operation is configured to answer with Access-Control-Max-Age header
When I send a request to this operation
Then Access-Control-Max-Age should be included in the response

Given an operation is configured to answer with Access-Control-Allow-Credentials header
When I send a request to this operation
Then Access-Control-Allow-Credentials should be included in the response

Given an operation is configured to answer with Access-Control-Allow-Methods header
When I send an OPTIONS request to this operation
And this request has Access-Control-Request-Method set to X (where X is a HTTP verb like DELETE)
Then Access-Control-Allow-Methods should be included in the response

Given an operation is configured to answer with Access-Control-Allow-Headers header
When I send an OPTIONS request to this operation
Then Access-Control-Allow-Headers should be included in the response

**Comment by philsturgeon** [comment]
We have a potential implementation for this over on #392 but @pytlesk4 do you think this covers enough? You have more experience with how this worked in Prism v2 so your input would be great.

**Comment by tbarn** [comment]
+1 

Definitely something I used to get asked often on support to help people set up with hosted Prism in Next

**Comment by dinfyru** [comment]
+1

**Comment by pytlesk4** [comment]
This looks great! Covers enough and then some!

**Comment by dinfyru** [comment]
Is there any promotion?

**Comment by XVincentX** [comment]
What do you mean by promotion?

**Comment by philsturgeon** [comment]
@pytlesk4 sorry were you saying that our requirements here looked good, or the potential implementation in #392 looked good?

@XVincentX I think that's a translation error. 

@dinfyru we're gonna get it done but as with most open-source projects these things take time.

**Comment by pytlesk4** [comment]
@philsturgeon Sorry, I was saying the requirements look good!

**Comment by dinfyru** [comment]
> 're gonna get it done but as with most open-source projects these things take time.

Thank you for your reply)

**Comment by wal0x** [comment]
is there a workaround possible while waiting for the next release ?

**Comment by stn1slv** [comment]
> is there a workaround possible while waiting for the next release ?

My workaround is installation and configuration Nginx before prism by the followed way:

- Nginx reply on OPTIONS request
`events {
    worker_connections 1024;
}

http {
    server {
        listen 3000;

        location /api {
            if ($request_method = 'OPTIONS') {
                add_header 'Access-Control-Allow-Origin' '*';
                add_header 'Access-Control-Allow-Credentials' 'true';
                add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS, PUT, DELETE, PATCH';
                add_header 'Access-Control-Allow-Headers' 'DNT,X-Mx-ReqToken,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type';
                add_header 'Access-Control-Max-Age' 1728000;
                add_header 'Content-Type' 'text/plain charset=UTF-8';
                add_header 'Content-Length' 0;
                return 204;
            }
            add_header 'Access-Control-Allow-Origin' '*' always;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_pass http://mock:4010/api;
        }
    }
}
`
- Other requests are forwarded to prism.

**Comment by wal0x** [comment]
> is there a workaround possible while waiting for the next release ?

I found an easy way for a workaround using nodeJs with express

```
var express = require('express');  
var request = require('request');
var cors = require('cors');

var app = express();  
// here the adresse to the end server
var targetServer = "http://localhost:4010";
// here this server (proxy) port number
var proxyPort = 4011;

app.use(cors());
app.use('/', function(req, res) {  
  var url = targetServer + req.url;
  req.pipe(request(url)).pipe(res);
});

app.listen(process.env.PORT || proxyPort);  
```

**Comment by XVincentX** [comment]
This is a low hanging fruit, it should really be about adding couple of headers to the responses by the HTTP server Prism is spawning.

**Comment by XVincentX** [comment]
@philsturgeon 

I think there was some confusion while writing the scenarios; I've put some considerations and thoughts so we can iterate on this.

> When I send a CORS request to an endpoint

Are we referring to the `OPTION` pre-flight request? Because not all the request require such thing.

---

The green should be the correct text:

```diff
Given I run Prism v3 with --cors-enabled=false
- When I send a CORS request to an operation
+ When I send an OPTION request to an operation which does not have the OPTION handler
- Then I should get a 401 response back
+ Then I should get a 404 response back
```

---

```
When I send a request to an endpoint
And Origin header in the request is the same domain as Prism
Then I should get back a 2xx response back
```

This (and other tests here) are not correct — the server will *always* respond to the HTTP request, no matter the CORS headers or not; what changes is whether the browser will *try to do* such request or not according to the domain/headers and stuff. This is not something we can test; it's code that's in the browser.

---

We also need to decide what Prism should do when CORS is enabled and a preflight request is received. According to this, we will then decide what to do with the harness.

## CORS flag enabled
* Prism can handle ALL the `OPTION` methods returning the necessary headers to the client, _skipping the OpenAPI document_
* Prism can handle ALL the `OPTION` methods returning the necessary headers to the client and then continue the pipeline processing through the provided OpenAPI document. The headers will be merged *but* if the OPTION method is not defined on the document, you'll get a 404, preventing the browser to do such request

If we go with the former, different tests checking out for headers presence according to the operation are not valida anymore (since they're handled directly by the http server skipping the OAS document)

If we go with the latter then they still make sense *but* it won't be that useful since I'll still have to define the `OPTIONS` method to all the operations I want CORS enabled. 

## CORS flag disabled
* If the current operation has an `OPTION` method defined, Prism will just respond regularly (so if no method defined, you get a 404) and, according to the returned response/headers, the browser will take its decisions.

**Comment by philsturgeon** [comment]
@XVincentX the first option certainly sounds better. Let's do that.

**Comment by XVincentX** [comment]
Gotcha. Tests will look a little bit different that the one posted here.

**Comment by philsturgeon** [comment]
That's ok, these can be considered more for guidance I think.
