### ISSUE TITLE
Prism does not even attempt to validate a body if "consumes" not defined.

### ISSUE THREAD

**Issue by brianmrock** [stoplightio/prism#420]
Prerequisites

The following spec:
```
{
  "swagger": "2.0",
  "paths": {
    "/pet/findByStatus": {
      "post": {
        "produces": ["application/json"],
        "parameters": [
          {
            "name": "status",
            "in": "query",
            "required": true,
            "type": "array",
            "items": {
              "type": "string",
              "enum": ["available", "pending", "sold"],
              "default": "available"
            },
            "collectionFormat": "multi"
          },
          {
            "in": "body",
            "name": "body",
            "schema": {
              "type": "object",
              "properties": {
                "id": {
                  "type": "integer",
                  "format": "int64"
                },
                "status": {
                  "type": "string",
                  "description": "Order Status",
                  "enum": ["placed", "approved", "delivered"]
                },
                "complete": {
                  "type": "boolean",
                  "default": false
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "schema": {
              "type": "string"
            }
          }
        }
      }
    }
  }
}
```
**Steps to reproduce**

1. Run Prism with the provided spec2. Make a request to PRISM `curl -X POST http://127.0.0.1:4010/pet/findByStatus?status=sold -H 'Content-Type: application/json' --data '{ "id": "should be a number" }'`3. Observe the output

**Expected**

{"type":"https://stoplight.io/prism/errors#UNPROCESSABLE_ENTITY","title":"Invalid request body payload","status":422,"detail":"Your request body is not valid: [{\"path\":[\"body\",\"id\"],\"code\":\"type\",\"message\":\"should be integer\",\"severity\":0}]"}

**Actual**

A lorem ipsum response similar to "exercitation reprehenderit dolore quis Lorem"

Context & Discussion

The problem stems for the fact that the OAS file lacks `"consumes": ["application/json"],`.When we attempt to validate the body  we first look at the expected media type of that body (as defined by OAS). Since the OAS does not specify the media type we can't find a validator and we don't even try to validate resulting in no validation errors.

 suggested that this is not a correct behavior and we should distinct between serialization and validation. In other words we should try to validate everything that can be serialized to a js object.

Read the Slack discussion for more contextAnd this one

Like  said:

... we Schema validate everything that has a Schema, and transform specific mine types that have known transformations (like xml and so far nothing else that I know of)

**Comment by XVincentX** [comment]
Ok I had a closer look to this one and the analysis is indeed correct. Apparently the validator process needs to match with the content type to be kicked off and right now we're only returning ok for `application/json` https://github.com/stoplightio/prism/blob/master/packages/http/src/validator/validators/schema.ts#L6

This is effectively really limitative since it won't kick off for other json compatible payloads, such as `application/vnd.error+json` or anything similar.

---

If we want this be part of 3.x release, we can

1. return always `true` from the [validation function](https://github.com/stoplightio/prism/blob/master/packages/http/src/validator/validators/schema.ts#L19) so that it's always going to be kicked off
2. Remove the `support` function entirely (this would be equal to return always `true`)

The long term solution in general would be to rethink the validation in general, but this is not the right time.

What do you think @chris-miaskowski @philsturgeon ?

**Comment by pytlesk4** [comment]
@XVincentX what about form data bodies? We should be able to validate those as well, we would just do something similar to header/query string validation.

**Comment by XVincentX** [comment]
#446 should fix it — but thanks for reminding me of non json payloads, I'll actually remember to write a test case for it!
