### ISSUE TITLE
Use path parameter example/default when displaying list of operations

### ISSUE THREAD

**Issue by philsturgeon** [stoplightio/prism#505]
**User story.**
As a CLI and Studio users, I want the URLs with path parameters to be instantly usable if possible so that I can click them, or copy them into a HTTP client.

**Is your feature request related to a problem?**

Currently we show URLs like this:

![Screen Shot 2019-07-30 at 20.59.07.png](https://images.zenhubusercontent.com/5d1f7c5b8a1fa426d066830f/9761f3c6-5c08-435f-97fe-362b373634e5)

In studio the current implementation is repeating the path with param templates showing up, then the full URL with the same stuff.

![Screen Shot 2019-07-30 at 20.57.49.png](https://images.zenhubusercontent.com/5d1f7c5b8a1fa426d066830f/eb83edec-fe94-4399-86eb-dc0ca8db4fc3)

**Describe the solution you'd like**

We should use example values, default, the first item from an enum, or if x-faker is there we can use a value from that. The goal here is to make the URL useful, without somebody having to copy and paste it, only to tweak bits and probably put an example value in there themselves.

This logic should go into the Prism JS API itself, so studio and Prism CLI do not both need to figure out how to do it.

**Comment by XVincentX** [comment]
Yeah, I like the feature. This might *not* be that easy though. We'll figure it out.

**Comment by philsturgeon** [comment]
the faker stuff is less important, just getting examples, default, enum in there should be main goal.

**Comment by XVincentX** [comment]
@StefanDywersant When working on this I really suggest you to write up a plan on how you're aiming to get these samples values — I just want to make sure we go on the right direction without writing code we're going to discard.

**Comment by StefanDywersant** [comment]
> @StefanDywersant When working on this I really suggest you to write up a plan on how you're aiming to get these samples values — I just want to make sure we go on the right direction without writing code we're going to discard.

- A utility which transforms IHttpOperation into example
- I would make it pluggable: an example plugins might include:
    - A simple string
    - A string with colors (so I can see which ones are parameters)
    - A curl line (with headers and stuff). Here comes the question whether it is prism’s responsibility?
- Above utility is responsible for putting path and params together and uses HttpParamGenerator
- Introduce HttpParamGenerator which will use JSONSchemaGenerator and additionally handle param styles, static examples from HttpContent
- We should be able to reuse HttpParamGenerator for generating headers (mocker/index.ts#computeMockedHeaders)

**Comment by XVincentX** [comment]
The good thing is that in the CLI we can use all the other packages since it's fundamentally the last one (core, http, http-server).

I would definitely keep out of the scope the idea of pluggable and just return string we're going to interpolate using any URI Template expander library (https://medialize.github.io/URI.js/uri-template.html)

`result = URI.expand("http://example.org/{file}", {file: "hello world.html"});`

Such string is then going to be fed to our `signale` logger — precisely [here](https://github.com/stoplightio/prism/blob/master/packages/cli/src/util/createServer.ts#L66)

Now the only thing that'd be "left" would be to grab each of these operations, take the resources and the required uri parameters (they should have a JSON Compabile schema) generate an example (static or dynamic? I vote for dynamic).

Apart these minor details, I think we're aligned @StefanDywersant — so please go ahead and rock this out 🎸
