### ISSUE TITLE
Support combination of static example and dynamic values

### ISSUE THREAD

**Issue by lehphyro** [stoplightio/prism#586]
**User story.**
As an API provider, I can do use static data in combination with dynamic data, so that I can provide more useful examples.

**Is your feature request related to a problem?**
I have a monetary amount object type that has two fields: amount and currency code. I'd like to have a dynamic amount and always `USD` as currency code.

**Describe the solution you'd like**
Perhaps have another field like "x-faker" called "x-static" and have that take precedence.

**Comment by pytlesk4** [comment]
@XVincentX we should enable some more json schema faker options. Or have a way to configure it.

[JSF Config](https://github.com/json-schema-faker/json-schema-faker/tree/master/docs#available-options)

Specifically `useExamplesValue` and `useDefaultValue`

@lehphyro all you would need to do is set a default or example for a property, and that will get used. Otherwise, the property will be generated.

**Comment by XVincentX** [comment]
I need to verify this. These values are already enabled.

**Comment by pytlesk4** [comment]
I verified it doesn't work then. Try mocking [this spec](https://gist.github.com/pytlesk4/ddbd7c6f791e68b2b34b0cbd6b11f250) with the latest prism.

- [ok](https://gist.github.com/pytlesk4/ddbd7c6f791e68b2b34b0cbd6b11f250#file-bear-dojo-v1-yaml-L26-L28): should default to `true`
- [honey.species](https://gist.github.com/pytlesk4/ddbd7c6f791e68b2b34b0cbd6b11f250#file-bear-dojo-v1-yaml-L36-L38): should default to `killer bees`

**Comment by StefanDywersant** [comment]
Yes, it is also not enabled in code: https://github.com/stoplightio/prism/blob/master/packages/http/src/mocker/generator/JSONSchema.ts#L12

**Comment by philsturgeon** [comment]
Hello everyone! So this is an interesting feature request, but there was a bit of confusion that came up here. Let's get that straightened out then move onto the request.

Basically the idea is "static" mocking is repeatable and the more information it has (enum, examples, default) the more useful that predictable mock response will be. 

When folks enable "dynamic" mode, Prism is always going to return different randomly generated data, and so we actually do not want to use the examples or default in that case.

Now, this feature request is about finding a way to let some be static and some be dynamic. I want to avoid making people litter their code with extensions, but this could be what #394 sets out to solve. 

I need input from others on this. Do we want to find some way to let folks mix and match static and dynamic, or should we just focus on #435 which gives full control over the mocking?

**Comment by pytlesk4** [comment]
> Now, this feature request is about finding a way to let some be static and some be dynamic. I want to avoid making people litter their code with extensions, but this could be what #394 sets out to solve.

This looks like a good solution to hold people over while we wait for #435.

> I need input from others on this. Do we want to find some way to let folks mix and match static and dynamic, or should we just focus on #435 which gives full control over the mocking?

I say lets find a way! If you are looking for a different kind of input, what kind of input you looking for?

**Comment by philsturgeon** [comment]
Do other people want to do this with an extension? If so, how should it look? `x-dynamic` as a boolean, or something else? I am leaning towards "im not sure I want this" but I think I could be convinced with a decent example :D

**Comment by pytlesk4** [comment]
@philsturgeon 

I am leaning towards "im not sure I want this" but I think I could be convinced with a decent example :D

**Comment by philsturgeon** [comment]
Ok, I think the best way to go about this is to focus on the generic mechanism in #394 then see what people get up to, and bake in support for whatever extension emerges as a clear winner. @lehphyro does that sound good to you?

**Comment by lehphyro** [comment]
I don't think so, all I have is a spec file and I'd like to just run prism with npm with it, not have my own server implementation with custom extensions.

**Comment by philsturgeon** [comment]
@lehphyro don't worry that was not the suggested approach. I think you saw the example of this extension concept being used in the JS API, but [we'll get it figured out for CLI users too](https://github.com/stoplightio/prism/pull/394#issuecomment-534104859).

**Comment by Brightside56** [comment]
@lehphyro there should be parameter in cli which lets you to use example values if set. If not set, then dynamic value will generated.
@philsturgeon without this parameter prism can be used mainly for writing fancy articles on medium, but not for 90% real life cases when someone needs to work with existing yaml API-specs.

**Comment by philsturgeon** [comment]
@Brightside56 we're always looking for ways to make Prism more useful to more people. I'm not sure anyone of us can confidently state that static+dynamic mixed response generation is absolutely required for 90% of use cases as you suggest, because if that were the case we would have heard a lot more about it from our users. So far this thread is the only one covering it. 

This specific issue had one specific recommended implementation, which is filling up the OpenAPI description with x-faker and x-static. When there's a small number of developers on a team this feels like it'll make sense, but when there are different teams wanting to use that same API description for multiple use cases this starts to become rather restrictive and cumbersome. 

If we were to consider the larger use cases, if people want more realistic mocking, they probably want data persistence and reuse: https://roadmap.stoplight.io/c/50-persisted-mock-data

Then if people send invalid currency codes, they'll get a realistic validation error, and when they send useful ones the response will be good without needing a) adding very specific examples, b) training the OpenAPI how to respond via x- extensions.

If you think that feature will solve your use case, please vote for it. Otherwise, if you have a specific implementation idea for how to handle static+dynamic mixed response generation then lets make a Discussion thread and bounce around some ideas.

Thanks!

**Comment by Brightside56** [comment]
@philsturgeon some mock servers have cli parameter which allows to use examples first if set (in case of dynamic response generation), and in my opinion it's best option. My case is I have dozens microservices/services to mock and I have their api specs in yaml. In some cases I need dynamic responses in some fields, but in general examples are ok, however with dynamic response generation Prism is generating unusable garbage.

My point is if example is set - then Prism could use example, if no example is set - Prism could generate response dynamically using field specs.

For example `-d` with `--prefer-examples`

**Comment by monkpit** [comment]
If anyone ends up here with a similar use case as me, I was able to get a mixture of example+dynamic data by setting

```json
x-json-schema-faker:
  use-examples-value: true
```

At the root level of my spec.

You can use `x-json-schema-faker` to pass any of the [options in the json-schema-faker docs](https://github.com/json-schema-faker/json-schema-faker/tree/master/docs#available-options)
