### ISSUE TITLE
Add ability to mock multiple API descriptions at one time

### ISSUE THREAD

**Issue by rossmcdonald** [stoplightio/prism#717]
**User story.**
As a developer implementing a micro-service architecture, I have several different API specifications that make up my application.

**Is your feature request related to a problem?**
Due to the number of APIs I have, it is not feasible for me to mock each API specification on a different port.

**Describe the solution you'd like**
I should be able to specify multiple API specifications to mock at once.

**Comment by XVincentX** [comment]
Thanks for the issue @rossmcdonald. 

At the moment we're not planning to offer this feature in Prism. The main challenge is, when loading multiple documents under the same server, the priority resolution.

What if two documents are defining a `/pet` path? Which of the two should have the precedence?

A possible solution would be name spacing all the documents, so that we'd have `/document1/pet` and `document2/pet` — but this would kind of make the mocking experience less "real", since the production server won't likely be using such prefix/namespace, requiring code changes when dealing with the real API.

We're definitively going to offer this as part of Hosted Prism/Prism in the cloud, which will hopefully become live in not so much time. Until this happens, I'll keep the issue opened.

I've pinned this in the issues page so other people interested into this will easily be able to check this out.

**Comment by rossmcdonald** [comment]
Thanks @XVincentX! Making this a feature of hosted Prism makes sense.

**Comment by pytlesk4** [comment]
@XVincentX The chances of someone having `/pets` defined in the two specs, and mocking them at the same time is relatively low. I think it would be better to allow a user to mock multiple specs, vs not. We would always warn the user prism will have a hard time figuring out a which `/pets` operation to mock if that actually happens.

**Comment by XVincentX** [comment]
I am going to write a small article in our documentation on how you can achieve the same result using a docker compose file and a reverse proxy.

**Comment by lag-of-death** [comment]
@XVincentX

https://github.com/stoplightio/prism/pull/730 implementation has some disadvantages:

- there are only 2 prism instances
- endpoints exposed by nginx are static - `/app_1` and `/app_2`

It can be run like so:
`PRISM_PROXY_PORT=8090 PRISM_DOC_1=./doc1.yaml PRISM_DOC_2=./doc2.yaml docker-compose up`

I haven't found anything that could allow for dynamic number of Prism instances that operate on different specification files (so basically take different paths to specification files).

What we could do is to generate `nginx.conf` and `docker-compose.yaml` with a script (accessible as a yarn task maybe).

`docker-compose` is just a yaml, so that should not be a problem and for `nginx`, we could use https://github.com/tmont/nginx-conf.

So, for example, we could have something like: 
`yarn run run-cluster ['doc1.yaml', 'doc2.yaml', 'doc3.yaml']` 
or maybe 
`yarn run run-cluster doc1.yaml endpoint_1 doc2.yaml endpoint_2 doc3.yaml endpoint_3`
to specify where a given specification should be accessible (ie. `doc1` accessbile on `/endpoint_1`);

**Comment by XVincentX** [comment]
We have updated the documentation to show how to make Prism serve multiple documents @rossmcdonald 

https://stoplight.io/p/docs/gh/stoplightio/prism/docs/guides/multiple-documents.md

**Comment by XVincentX** [comment]
Implemented in Hosted Mocks 1.11

**Comment by RanjaniGP** [comment]
Hi, Currently I am evaluating prism for mocking API. I was able to cover other topics. But, mocking multiple API at one time was not able to do using docker compose. Could you please give a clear picture on how to start 2 API descriptions at a time and requesting endpoints of both the servers?

**Comment by childish-sambino** [comment]
Note that docs for this are now found here: https://meta.stoplight.io/docs/prism/4bf78efbf9dd2-serving-multiple-open-api-documents
