### ISSUE TITLE
Prism conductor server aynsc/callback support

### ISSUE THREAD

**Issue by marbemac** [stoplightio/prism#76]
Right now we cap the conductor server at 30 seconds per collection run, and it is sync. We should add an async + callback url option, to cover longer running collection runs (more of a thing once data driven collections are implemented).

**Comment by rossmcdonald** [comment]
Regarding supporting this in the CLI, the`gcloud` (Google Cloud CLI) utility has an `--async` flag that is very handy for marking a command as asynchronous. The way `gcloud` works specifically is it just prints a transaction URL and continues on, and it's up to the user to save the URL or throw it away.

We could do something similar where the `prism conduct` CLI with the flags:

* `--callback <callback URL>`, which sets a callback URL on run completion.
* `--async`, which marks the run as asynchronous. 

So:

```
# Run sync with callback
prism conduct ... --callback https://example.com/done

# Run async with callback
prism conduct ... --async --callback https://example.com/done

# Run async
prism conduct ... --async
```

Since we don't have the concept of a transaction URL yet, we could require that `--callback` is set if `--async` is. Or we could let people throw away the results if they wanted to (I'm not sure if there is a use-case for that).

**Comment by marbemac** [comment]
Use case for throwing away results is outside of testing (more general purpose automation). The syntax presented there looks great though!

**Comment by pytlesk4** [comment]
Once we have logging, then the --async flag, will make a lot more sense in testing. Because we would generate a log url(same as gcloud producing a transaction URL). Also, the ability to automate something is more of a bonus, not something we message.

How about we support the first two use cases:

- Run sync with a callback?
- Run async with a callback?
