### ISSUE TITLE
Prism doesn't provide error details if a 400 response is specified

### ISSUE THREAD

**Issue by lehphyro** [stoplightio/prism#807]
**Describe the bug**
According to https://community.stoplight.io/t/force-prisms-detailed-422-response/919 prism has a regression regarding error details. In version 2, it provided a response header with an explanation on why the request is invalid, it doesn't do that in version 3 anymore.

**To Reproduce**

1. Given this OpenAPI document:
```
openapi: 3.0.1
info:
  title: Test
  version: "1.0"
paths:
  /test:
    post:
      operationId: postTest
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: integer
              required:
                - id
      responses:
          '204':
            description: Operation was successful
          '400':
            description: BadRequest
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    message:
                      description: Any further information
                      type: string
                  required:
                    - message
```
2. Run this CLI command: `prism mock openapi.yaml`
3. Execute the request: 
```
POST http://localhost:4010/test
{
    "id": "<integer>"
}
```

**Expected behavior**
A response body like the following:
```
{
    "type": "https://stoplight.io/prism/errors#UNPROCESSABLE_ENTITY",
    "title": "Invalid request body payload",
    "status": 422,
    "detail": "Your request body is not valid and no HTTP validation response was found in the spec, so Prism is generating this error for you.",
    "validation": [
        {
            "location": [
                "body",
                "id"
            ],
            "severity": "Error",
            "code": "type",
            "message": "should be integer"
        }
    ]
}
```

We get this Instead:
```
{
    "message": "string"
}
```

We get the detailed response if we remove the `400` response from the spec.

Maybe we could send a parameter or header in the request to tell prism that it should provide the default response if the request is invalid?

**Comment by XVincentX** [comment]
@lehphyro We effective give preference to user defined responses (422-400-default) and return these *before* generating a 422 response with the error detail. This is on purpose and not a bug. @philsturgeon what do you think? Maybe we can try to have the cake and eat it too?

**Comment by philsturgeon** [comment]
@lehphyro I understand the confusion, but... "and no HTTP validation response was found in the spec" there _was_ a response defined in the spec, so it used it. 

Prism v3.0 is a brand new major version, not trying to emulate what v2.0 did. We have intentionally redesigned a lot of functionality in order to make a better product. We moved to a better logging system which explains the decisions Prism is making in the log output. If these logs are not providing enough information, or are not discoverable enough, then we should look into alternatives. 

What could a "have cake and eat it" solution look like? We do not want to ignore the users 400 and shove our own 400 over the top do we?

**Comment by marbemac** [comment]
> In version 2, it provided a response header with an explanation on why the request is invalid

@XVincentX doesn't upcoming v3.2 accomplish this? Adds a response header with validation issues.

Seems to be a conflict in original issue - the example given seems to hijack the entire response body (and not add a response header with validation issues as described). I think we should be able to get the response header solution in place, maybe as soon as 3.2 if it does what I understand it to do.

**Comment by XVincentX** [comment]
This is what I meant for have the cake and eat it too. Effectively, we're still appending all the validations errors in the `sl-violations` header

**Comment by philsturgeon** [comment]
We add a sl-violations header to the proxy which reports mismatches between what is defined as the contract and what passes through in the form of a request or a response.

The mock server only offers its own validation response if you’ve not provided one, which is how it generally works for any status code. If Prism decides to return an X for whatever reason, if you have an X it’ll use that X. If you don’t it’ll make its own X with a Prism error.

Validation is tricky because I think the prism error (with actual validation information) is more useful than the static response with an example we generated. This logic predates me at the company and I’ve never been sure how to make it better.

Tom mentioned that prism v2 would try to inject prism errors into the static response (I suppose looking for an “error” or “message” string to replace) but I’ve not seen this in the wild.

**Comment by XVincentX** [comment]
> We add a sl-violations header to the proxy which reports mismatches between what is defined as the contract and what passes through in the form of a request or a response.

We also add it when not proxying stuff and even if we're using an user-provided response!

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/1416224/69433471-f140aa80-0d3b-11ea-9895-a5380edd45e8.png">

**Comment by garyhoren** [comment]
Can you give prism a command line switch to allow the user to change the behavior?

**Comment by lehphyro** [comment]
Are you planning to fix it soon?

**Comment by XVincentX** [comment]
@lehphyro I'm sorry but I haven't been able to look at this just yet.

**Comment by philsturgeon** [comment]
It seems like the use case is covered with the recent addition of sl-violation. 

The actual response coming back from the 400 could be made more interesting with more keywords.

```json
{
    "message": "string"
}
```

So if you added an example to the `message` field, or an example of the entire response, it would be showing you a more useful validation error. It would not have specifics of the exact thing, but that can be found in the header.

The question is, would you prefer clients interacted with the Prism error format for integration, or _your_ error format. We fall back to generating our own errors only because we need to respond with something, but we aren0t trying to design the API for you :D 

Hope this helps!

**Comment by lehphyro** [comment]
The `sl-violations` header is good enough for me, thanks!
