### ISSUE TITLE
request payload validation should detect undefined properties

### ISSUE THREAD

**Issue by garyhoren** [stoplightio/prism#835]
I am running prism V 3.1.1 on Mac with the following arguments:
prism mock https://raw.githack.com/OAI/OpenAPI-Specification/master/examples/v3.0/petstore-expanded.yaml

when I submit a request with an undefined property "txg" I get a 200:

curl -X POST -s -D "/dev/stderr" -H "content-type: application/json" -d '{"txg":"Stowford", "name" : "sadf"}' http://127.0.0.1:4010/pets

gives:

HTTP/1.1 200 OK
access-control-allow-origin: *
content-type: application/json
content-length: 58
Date: Thu, 21 Nov 2019 16:28:25 GMT
Connection: keep-alive

{"name":"string","tag":"string","id":-9223372036854776000}ansible|ghoren-ltm:~ ghoren$

Shouldn't prims flag properties that are not defined in the swagger file? What I want to do is detect API changes that break compatibility, and it seems like an undefined property (i.e. one that was there in an earlier version and has been removed) should be part of that. It does detect required properties that are missing, but not incorrect optional ones.

**Comment by XVincentX** [comment]
I am assuming you're referring to the fact that you're sending a property not declared in the JSON Schema and Prism is not telling you anything about it.

Well the issue is in the schema! You should modify the schema to say that additional (foreign) properties are not allowed. This is something that unfortunately is not supported in the `Schema` Object that's included in OpenAPI 2/3 but it's supported in the current JSON Schema Draft 6,7,8 that will be hopefully supported in 3.1.
