### ISSUE TITLE
option to specify basepath in prism mock server

### ISSUE THREAD

**Issue by dario-frongillo** [stoplightio/prism#906]
**User story.**
Hi all,
in my yaml i ve specified
servers:
  - url: https://localhost:3000/poll-maker/v1

so if exist a path /hello i want that mock server respond to 
 https://localhost:3000/poll-maker/v1/hello

how can specify basepath poll-maker/v1 in mock server ?

**Comment by XVincentX** [comment]
Hey @dario-frongillo,

Prism non supporta nessun `basePath`, né per OpenAPI 2 né per OpenAPI 3.0, [qui trovi le nostre motivazioni a riguardo](https://github.com/stoplightio/prism#faqs).

Scrivici ancora se hai bisogno di chiarimenti a riguardo.

**Comment by mullerch** [comment]
Still this feature would be useful so that the mock server corresponds as much as possible to the production infrastructure.

This could be done with a CLI option:
  --basepath, -b

Usage: prism -b /poll-maker/v1

**Comment by ynarwal** [comment]
I agree with @mullerch here it's really handy to have this feature available @XVincentX are you open to a PR ?

**Comment by XVincentX** [comment]
As mentioned [here](https://github.com/stoplightio/prism#faqs) — we are not going to support such feature.

**Comment by boeboe** [comment]
@XVincentX ... the argument not to support this does not make sense to me. Basepath and server are both essential elements in the V2 and V3 specification. Not supporting it because "it is confusing to some others" does not make sense. It is very little implementation work to implement this and you can still keep the default behavior to ignore it, if you wish. The only way to support a real mock server now (and having the right full URL paths is essential for that), is to front prism with a reverse proxy to do URL rewriting. 

I am going to need to look for alternatives, as the goal of a mock server is to stay as close to the specifications, not to make exceptions and chose to ignore essential elements. Clients, like SwaggerUI and others, all are implemented taking the basepath or server correctly into account.

**Comment by XVincentX** [comment]
Hey @boeboe,

I'd be interested in learning more about how the lack of `basePath` support is preventing you from completing your work.

I'm open to new ideas and — in case there's a convincing argument, we can reconsider.
